language: ruby
before_install:
  - sudo apt-get install libhunspell-dev hunspell-en-us
  - gem install ffi rubygems-tasks rspec yard
rvm:
  - 2.5
  - 2.6
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
script: rake spec
